on:
  push:
    branches:
      - master

name: Build and deploy

jobs:
  build:
    name: Build and test
    runs-on: [ubuntu-latest]

    steps:
    - name: Checkout
      uses: actions/checkout@v2
      with:
        submodules: true

    - name: Build
      run: |
        yarn install
        yarn build

    - name: Deploy
      run: |
        yarn gh-pages \
          --silent \
          --repo 'https://x-access-token:${{ secrets.DEPLOY_TOKEN }}@github.com/${{ github.repository }}.git' \
          --branch 'gh-pages' \
          --user 'Johannes Barop <jb@barop.de>' \
          --dist 'build' --message 'Uploading new version: ${{ github.sha }}'
